// Code generated by MockGen. DO NOT EDIT.
// Source: ../mutation.go
//
// Generated by this command:
//
//	mockgen -source=../mutation.go -destination=mock_mutation.go
//

// Package mock_entitystore is a generated GoMock package.
package mock_entitystore
