// Code generated by MockGen. DO NOT EDIT.
// Source: ../query.go
//
// Generated by this command:
//
//	mockgen -source=../query.go -destination=mock_query.go
//

// Package mock_entitystore is a generated GoMock package.
package mock_entitystore

import (
	reflect "reflect"

	datastore "cloud.google.com/go/datastore"
	entitystore "go.fujikura.biz/entitystore"
	gomock "go.uber.org/mock/gomock"
)

// MockQuery is a mock of Query interface.
type MockQuery struct {
	ctrl     *gomock.Controller
	recorder *MockQueryMockRecorder
	isgomock struct{}
}

// MockQueryMockRecorder is the mock recorder for MockQuery.
type MockQueryMockRecorder struct {
	mock *MockQuery
}

// NewMockQuery creates a new mock instance.
func NewMockQuery(ctrl *gomock.Controller) *MockQuery {
	mock := &MockQuery{ctrl: ctrl}
	mock.recorder = &MockQueryMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockQuery) EXPECT() *MockQueryMockRecorder {
	return m.recorder
}

// Ancestor mocks base method.
func (m *MockQuery) Ancestor(ancestor *datastore.Key) entitystore.Query {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Ancestor", ancestor)
	ret0, _ := ret[0].(entitystore.Query)
	return ret0
}

// Ancestor indicates an expected call of Ancestor.
func (mr *MockQueryMockRecorder) Ancestor(ancestor any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Ancestor", reflect.TypeOf((*MockQuery)(nil).Ancestor), ancestor)
}

// Distinct mocks base method.
func (m *MockQuery) Distinct() entitystore.Query {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Distinct")
	ret0, _ := ret[0].(entitystore.Query)
	return ret0
}

// Distinct indicates an expected call of Distinct.
func (mr *MockQueryMockRecorder) Distinct() *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Distinct", reflect.TypeOf((*MockQuery)(nil).Distinct))
}

// DistinctOn mocks base method.
func (m *MockQuery) DistinctOn(fieldNames ...string) entitystore.Query {
	m.ctrl.T.Helper()
	varargs := []any{}
	for _, a := range fieldNames {
		varargs = append(varargs, a)
	}
	ret := m.ctrl.Call(m, "DistinctOn", varargs...)
	ret0, _ := ret[0].(entitystore.Query)
	return ret0
}

// DistinctOn indicates an expected call of DistinctOn.
func (mr *MockQueryMockRecorder) DistinctOn(fieldNames ...any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "DistinctOn", reflect.TypeOf((*MockQuery)(nil).DistinctOn), fieldNames...)
}

// End mocks base method.
func (m *MockQuery) End(c datastore.Cursor) entitystore.Query {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "End", c)
	ret0, _ := ret[0].(entitystore.Query)
	return ret0
}

// End indicates an expected call of End.
func (mr *MockQueryMockRecorder) End(c any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "End", reflect.TypeOf((*MockQuery)(nil).End), c)
}

// EventualConsistency mocks base method.
func (m *MockQuery) EventualConsistency() entitystore.Query {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "EventualConsistency")
	ret0, _ := ret[0].(entitystore.Query)
	return ret0
}

// EventualConsistency indicates an expected call of EventualConsistency.
func (mr *MockQueryMockRecorder) EventualConsistency() *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "EventualConsistency", reflect.TypeOf((*MockQuery)(nil).EventualConsistency))
}

// Filter mocks base method.
func (m *MockQuery) Filter(filterStr string, value any) entitystore.Query {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Filter", filterStr, value)
	ret0, _ := ret[0].(entitystore.Query)
	return ret0
}

// Filter indicates an expected call of Filter.
func (mr *MockQueryMockRecorder) Filter(filterStr, value any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Filter", reflect.TypeOf((*MockQuery)(nil).Filter), filterStr, value)
}

// FilterEntity mocks base method.
func (m *MockQuery) FilterEntity(ef datastore.EntityFilter) entitystore.Query {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "FilterEntity", ef)
	ret0, _ := ret[0].(entitystore.Query)
	return ret0
}

// FilterEntity indicates an expected call of FilterEntity.
func (mr *MockQueryMockRecorder) FilterEntity(ef any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "FilterEntity", reflect.TypeOf((*MockQuery)(nil).FilterEntity), ef)
}

// FilterField mocks base method.
func (m *MockQuery) FilterField(fieldName, operator string, value any) entitystore.Query {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "FilterField", fieldName, operator, value)
	ret0, _ := ret[0].(entitystore.Query)
	return ret0
}

// FilterField indicates an expected call of FilterField.
func (mr *MockQueryMockRecorder) FilterField(fieldName, operator, value any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "FilterField", reflect.TypeOf((*MockQuery)(nil).FilterField), fieldName, operator, value)
}

// KeysOnly mocks base method.
func (m *MockQuery) KeysOnly() entitystore.Query {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "KeysOnly")
	ret0, _ := ret[0].(entitystore.Query)
	return ret0
}

// KeysOnly indicates an expected call of KeysOnly.
func (mr *MockQueryMockRecorder) KeysOnly() *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "KeysOnly", reflect.TypeOf((*MockQuery)(nil).KeysOnly))
}

// Limit mocks base method.
func (m *MockQuery) Limit(limit int) entitystore.Query {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Limit", limit)
	ret0, _ := ret[0].(entitystore.Query)
	return ret0
}

// Limit indicates an expected call of Limit.
func (mr *MockQueryMockRecorder) Limit(limit any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Limit", reflect.TypeOf((*MockQuery)(nil).Limit), limit)
}

// Namespace mocks base method.
func (m *MockQuery) Namespace(ns string) entitystore.Query {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Namespace", ns)
	ret0, _ := ret[0].(entitystore.Query)
	return ret0
}

// Namespace indicates an expected call of Namespace.
func (mr *MockQueryMockRecorder) Namespace(ns any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Namespace", reflect.TypeOf((*MockQuery)(nil).Namespace), ns)
}

// NewAggregationQuery mocks base method.
func (m *MockQuery) NewAggregationQuery() *datastore.AggregationQuery {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "NewAggregationQuery")
	ret0, _ := ret[0].(*datastore.AggregationQuery)
	return ret0
}

// NewAggregationQuery indicates an expected call of NewAggregationQuery.
func (mr *MockQueryMockRecorder) NewAggregationQuery() *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "NewAggregationQuery", reflect.TypeOf((*MockQuery)(nil).NewAggregationQuery))
}

// Offset mocks base method.
func (m *MockQuery) Offset(offset int) entitystore.Query {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Offset", offset)
	ret0, _ := ret[0].(entitystore.Query)
	return ret0
}

// Offset indicates an expected call of Offset.
func (mr *MockQueryMockRecorder) Offset(offset any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Offset", reflect.TypeOf((*MockQuery)(nil).Offset), offset)
}

// Order mocks base method.
func (m *MockQuery) Order(fieldName string) entitystore.Query {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Order", fieldName)
	ret0, _ := ret[0].(entitystore.Query)
	return ret0
}

// Order indicates an expected call of Order.
func (mr *MockQueryMockRecorder) Order(fieldName any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Order", reflect.TypeOf((*MockQuery)(nil).Order), fieldName)
}

// Project mocks base method.
func (m *MockQuery) Project(fieldNames ...string) entitystore.Query {
	m.ctrl.T.Helper()
	varargs := []any{}
	for _, a := range fieldNames {
		varargs = append(varargs, a)
	}
	ret := m.ctrl.Call(m, "Project", varargs...)
	ret0, _ := ret[0].(entitystore.Query)
	return ret0
}

// Project indicates an expected call of Project.
func (mr *MockQueryMockRecorder) Project(fieldNames ...any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Project", reflect.TypeOf((*MockQuery)(nil).Project), fieldNames...)
}

// Q mocks base method.
func (m *MockQuery) Q() *datastore.Query {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Q")
	ret0, _ := ret[0].(*datastore.Query)
	return ret0
}

// Q indicates an expected call of Q.
func (mr *MockQueryMockRecorder) Q() *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Q", reflect.TypeOf((*MockQuery)(nil).Q))
}

// Start mocks base method.
func (m *MockQuery) Start(c datastore.Cursor) entitystore.Query {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Start", c)
	ret0, _ := ret[0].(entitystore.Query)
	return ret0
}

// Start indicates an expected call of Start.
func (mr *MockQueryMockRecorder) Start(c any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Start", reflect.TypeOf((*MockQuery)(nil).Start), c)
}

// Transaction mocks base method.
func (m *MockQuery) Transaction(t *datastore.Transaction) entitystore.Query {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Transaction", t)
	ret0, _ := ret[0].(entitystore.Query)
	return ret0
}

// Transaction indicates an expected call of Transaction.
func (mr *MockQueryMockRecorder) Transaction(t any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Transaction", reflect.TypeOf((*MockQuery)(nil).Transaction), t)
}
