// Code generated by MockGen. DO NOT EDIT.
// Source: ../entity_lister.go
//
// Generated by this command:
//
//	mockgen -source=../entity_lister.go -destination=mock_entity_lister.go
//

// Package mock_entitystore is a generated GoMock package.
package mock_entitystore

import (
	context "context"
	reflect "reflect"

	datastore "cloud.google.com/go/datastore"
	entitystore "go.fujikura.biz/entitystore"
	gomock "go.uber.org/mock/gomock"
)

// MockEntityLister is a mock of EntityLister interface.
type MockEntityLister[E entitystore.Entity] struct {
	ctrl     *gomock.Controller
	recorder *MockEntityListerMockRecorder[E]
	isgomock struct{}
}

// MockEntityListerMockRecorder is the mock recorder for MockEntityLister.
type MockEntityListerMockRecorder[E entitystore.Entity] struct {
	mock *MockEntityLister[E]
}

// NewMockEntityLister creates a new mock instance.
func NewMockEntityLister[E entitystore.Entity](ctrl *gomock.Controller) *MockEntityLister[E] {
	mock := &MockEntityLister[E]{ctrl: ctrl}
	mock.recorder = &MockEntityListerMockRecorder[E]{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockEntityLister[E]) EXPECT() *MockEntityListerMockRecorder[E] {
	return m.recorder
}

// GetKeyList mocks base method.
func (m *MockEntityLister[E]) GetKeyList(ctx context.Context, limit int, cur string) ([]*datastore.Key, string, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetKeyList", ctx, limit, cur)
	ret0, _ := ret[0].([]*datastore.Key)
	ret1, _ := ret[1].(string)
	ret2, _ := ret[2].(error)
	return ret0, ret1, ret2
}

// GetKeyList indicates an expected call of GetKeyList.
func (mr *MockEntityListerMockRecorder[E]) GetKeyList(ctx, limit, cur any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetKeyList", reflect.TypeOf((*MockEntityLister[E])(nil).GetKeyList), ctx, limit, cur)
}

// GetList mocks base method.
func (m *MockEntityLister[E]) GetList(ctx context.Context, limit int, cur string) ([]E, string, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetList", ctx, limit, cur)
	ret0, _ := ret[0].([]E)
	ret1, _ := ret[1].(string)
	ret2, _ := ret[2].(error)
	return ret0, ret1, ret2
}

// GetList indicates an expected call of GetList.
func (mr *MockEntityListerMockRecorder[E]) GetList(ctx, limit, cur any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetList", reflect.TypeOf((*MockEntityLister[E])(nil).GetList), ctx, limit, cur)
}

// WithFilter mocks base method.
func (m *MockEntityLister[E]) WithFilter(f func(*datastore.Key) bool) entitystore.EntityLister[E] {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "WithFilter", f)
	ret0, _ := ret[0].(entitystore.EntityLister[E])
	return ret0
}

// WithFilter indicates an expected call of WithFilter.
func (mr *MockEntityListerMockRecorder[E]) WithFilter(f any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "WithFilter", reflect.TypeOf((*MockEntityLister[E])(nil).WithFilter), f)
}
