// Code generated by MockGen. DO NOT EDIT.
// Source: ../transaction.go
//
// Generated by this command:
//
//	mockgen -source=../transaction.go -destination=mock_transaction.go
//

// Package mock_entitystore is a generated GoMock package.
package mock_entitystore

import (
	reflect "reflect"

	datastore "cloud.google.com/go/datastore"
	entitystore "go.fujikura.biz/entitystore"
	gomock "go.uber.org/mock/gomock"
)

// MockTransaction is a mock of Transaction interface.
type MockTransaction struct {
	ctrl     *gomock.Controller
	recorder *MockTransactionMockRecorder
	isgomock struct{}
}

// MockTransactionMockRecorder is the mock recorder for MockTransaction.
type MockTransactionMockRecorder struct {
	mock *MockTransaction
}

// NewMockTransaction creates a new mock instance.
func NewMockTransaction(ctrl *gomock.Controller) *MockTransaction {
	mock := &MockTransaction{ctrl: ctrl}
	mock.recorder = &MockTransactionMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockTransaction) EXPECT() *MockTransactionMockRecorder {
	return m.recorder
}

// Delete mocks base method.
func (m *MockTransaction) Delete(key *datastore.Key) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Delete", key)
	ret0, _ := ret[0].(error)
	return ret0
}

// Delete indicates an expected call of Delete.
func (mr *MockTransactionMockRecorder) Delete(key any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Delete", reflect.TypeOf((*MockTransaction)(nil).Delete), key)
}

// DeleteMulti mocks base method.
func (m *MockTransaction) DeleteMulti(keys []*datastore.Key) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "DeleteMulti", keys)
	ret0, _ := ret[0].(error)
	return ret0
}

// DeleteMulti indicates an expected call of DeleteMulti.
func (mr *MockTransactionMockRecorder) DeleteMulti(keys any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "DeleteMulti", reflect.TypeOf((*MockTransaction)(nil).DeleteMulti), keys)
}

// Get mocks base method.
func (m *MockTransaction) Get(key *datastore.Key, dst any) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Get", key, dst)
	ret0, _ := ret[0].(error)
	return ret0
}

// Get indicates an expected call of Get.
func (mr *MockTransactionMockRecorder) Get(key, dst any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Get", reflect.TypeOf((*MockTransaction)(nil).Get), key, dst)
}

// GetMulti mocks base method.
func (m *MockTransaction) GetMulti(keys []*datastore.Key, dst any) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetMulti", keys, dst)
	ret0, _ := ret[0].(error)
	return ret0
}

// GetMulti indicates an expected call of GetMulti.
func (mr *MockTransactionMockRecorder) GetMulti(keys, dst any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetMulti", reflect.TypeOf((*MockTransaction)(nil).GetMulti), keys, dst)
}

// Mutate mocks base method.
func (m *MockTransaction) Mutate(muts ...*datastore.Mutation) ([]*datastore.PendingKey, error) {
	m.ctrl.T.Helper()
	varargs := []any{}
	for _, a := range muts {
		varargs = append(varargs, a)
	}
	ret := m.ctrl.Call(m, "Mutate", varargs...)
	ret0, _ := ret[0].([]*datastore.PendingKey)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// Mutate indicates an expected call of Mutate.
func (mr *MockTransactionMockRecorder) Mutate(muts ...any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Mutate", reflect.TypeOf((*MockTransaction)(nil).Mutate), muts...)
}

// Put mocks base method.
func (m *MockTransaction) Put(key *datastore.Key, src any) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Put", key, src)
	ret0, _ := ret[0].(error)
	return ret0
}

// Put indicates an expected call of Put.
func (mr *MockTransactionMockRecorder) Put(key, src any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Put", reflect.TypeOf((*MockTransaction)(nil).Put), key, src)
}

// PutMulti mocks base method.
func (m *MockTransaction) PutMulti(keys []*datastore.Key, src any) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "PutMulti", keys, src)
	ret0, _ := ret[0].(error)
	return ret0
}

// PutMulti indicates an expected call of PutMulti.
func (mr *MockTransactionMockRecorder) PutMulti(keys, src any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "PutMulti", reflect.TypeOf((*MockTransaction)(nil).PutMulti), keys, src)
}

// Query mocks base method.
func (m *MockTransaction) Query(kind string) entitystore.Query {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Query", kind)
	ret0, _ := ret[0].(entitystore.Query)
	return ret0
}

// Query indicates an expected call of Query.
func (mr *MockTransactionMockRecorder) Query(kind any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Query", reflect.TypeOf((*MockTransaction)(nil).Query), kind)
}

// Raw mocks base method.
func (m *MockTransaction) Raw() *datastore.Transaction {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Raw")
	ret0, _ := ret[0].(*datastore.Transaction)
	return ret0
}

// Raw indicates an expected call of Raw.
func (mr *MockTransactionMockRecorder) Raw() *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Raw", reflect.TypeOf((*MockTransaction)(nil).Raw))
}

// TrackKey mocks base method.
func (m *MockTransaction) TrackKey(key *datastore.Key) {
	m.ctrl.T.Helper()
	m.ctrl.Call(m, "TrackKey", key)
}

// TrackKey indicates an expected call of TrackKey.
func (mr *MockTransactionMockRecorder) TrackKey(key any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "TrackKey", reflect.TypeOf((*MockTransaction)(nil).TrackKey), key)
}
