// Code generated by MockGen. DO NOT EDIT.
// Source: ../aggregation.go
//
// Generated by this command:
//
//	mockgen -source=../aggregation.go -destination=mock_aggregation.go
//

// Package mock_entitystore is a generated GoMock package.
package mock_entitystore

import (
	context "context"
	reflect "reflect"

	entitystore "go.fujikura.biz/entitystore"
	gomock "go.uber.org/mock/gomock"
)

// MockAggregation is a mock of Aggregation interface.
type MockAggregation struct {
	ctrl     *gomock.Controller
	recorder *MockAggregationMockRecorder
	isgomock struct{}
}

// MockAggregationMockRecorder is the mock recorder for MockAggregation.
type MockAggregationMockRecorder struct {
	mock *MockAggregation
}

// NewMockAggregation creates a new mock instance.
func NewMockAggregation(ctrl *gomock.Controller) *MockAggregation {
	mock := &MockAggregation{ctrl: ctrl}
	mock.recorder = &MockAggregationMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockAggregation) EXPECT() *MockAggregationMockRecorder {
	return m.recorder
}

// Avg mocks base method.
func (m *MockAggregation) Avg(f string) float64 {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Avg", f)
	ret0, _ := ret[0].(float64)
	return ret0
}

// Avg indicates an expected call of Avg.
func (mr *MockAggregationMockRecorder) Avg(f any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Avg", reflect.TypeOf((*MockAggregation)(nil).Avg), f)
}

// Count mocks base method.
func (m *MockAggregation) Count() int {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Count")
	ret0, _ := ret[0].(int)
	return ret0
}

// Count indicates an expected call of Count.
func (mr *MockAggregationMockRecorder) Count() *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Count", reflect.TypeOf((*MockAggregation)(nil).Count))
}

// Float64Sum mocks base method.
func (m *MockAggregation) Float64Sum(f string) float64 {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Float64Sum", f)
	ret0, _ := ret[0].(float64)
	return ret0
}

// Float64Sum indicates an expected call of Float64Sum.
func (mr *MockAggregationMockRecorder) Float64Sum(f any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Float64Sum", reflect.TypeOf((*MockAggregation)(nil).Float64Sum), f)
}

// IntSum mocks base method.
func (m *MockAggregation) IntSum(f string) int {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "IntSum", f)
	ret0, _ := ret[0].(int)
	return ret0
}

// IntSum indicates an expected call of IntSum.
func (mr *MockAggregationMockRecorder) IntSum(f any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "IntSum", reflect.TypeOf((*MockAggregation)(nil).IntSum), f)
}

// Run mocks base method.
func (m *MockAggregation) Run(ctx context.Context) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Run", ctx)
	ret0, _ := ret[0].(error)
	return ret0
}

// Run indicates an expected call of Run.
func (mr *MockAggregationMockRecorder) Run(ctx any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Run", reflect.TypeOf((*MockAggregation)(nil).Run), ctx)
}

// WithAvg mocks base method.
func (m *MockAggregation) WithAvg(f string) entitystore.Aggregation {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "WithAvg", f)
	ret0, _ := ret[0].(entitystore.Aggregation)
	return ret0
}

// WithAvg indicates an expected call of WithAvg.
func (mr *MockAggregationMockRecorder) WithAvg(f any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "WithAvg", reflect.TypeOf((*MockAggregation)(nil).WithAvg), f)
}

// WithCount mocks base method.
func (m *MockAggregation) WithCount() entitystore.Aggregation {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "WithCount")
	ret0, _ := ret[0].(entitystore.Aggregation)
	return ret0
}

// WithCount indicates an expected call of WithCount.
func (mr *MockAggregationMockRecorder) WithCount() *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "WithCount", reflect.TypeOf((*MockAggregation)(nil).WithCount))
}

// WithFloat64Sum mocks base method.
func (m *MockAggregation) WithFloat64Sum(f string) entitystore.Aggregation {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "WithFloat64Sum", f)
	ret0, _ := ret[0].(entitystore.Aggregation)
	return ret0
}

// WithFloat64Sum indicates an expected call of WithFloat64Sum.
func (mr *MockAggregationMockRecorder) WithFloat64Sum(f any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "WithFloat64Sum", reflect.TypeOf((*MockAggregation)(nil).WithFloat64Sum), f)
}

// WithIntSum mocks base method.
func (m *MockAggregation) WithIntSum(f string) entitystore.Aggregation {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "WithIntSum", f)
	ret0, _ := ret[0].(entitystore.Aggregation)
	return ret0
}

// WithIntSum indicates an expected call of WithIntSum.
func (mr *MockAggregationMockRecorder) WithIntSum(f any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "WithIntSum", reflect.TypeOf((*MockAggregation)(nil).WithIntSum), f)
}
