// Code generated by MockGen. DO NOT EDIT.
// Source: ../datastore_client.go
//
// Generated by this command:
//
//	mockgen -source=../datastore_client.go -destination=mock_datastore_client.go
//

// Package mock_entitystore is a generated GoMock package.
package mock_entitystore

import (
	context "context"
	reflect "reflect"

	datastore "cloud.google.com/go/datastore"
	entitystore "go.fujikura.biz/entitystore"
	gomock "go.uber.org/mock/gomock"
)

// MockDatastoreClient is a mock of DatastoreClient interface.
type MockDatastoreClient struct {
	ctrl     *gomock.Controller
	recorder *MockDatastoreClientMockRecorder
	isgomock struct{}
}

// MockDatastoreClientMockRecorder is the mock recorder for MockDatastoreClient.
type MockDatastoreClientMockRecorder struct {
	mock *MockDatastoreClient
}

// NewMockDatastoreClient creates a new mock instance.
func NewMockDatastoreClient(ctrl *gomock.Controller) *MockDatastoreClient {
	mock := &MockDatastoreClient{ctrl: ctrl}
	mock.recorder = &MockDatastoreClientMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockDatastoreClient) EXPECT() *MockDatastoreClientMockRecorder {
	return m.recorder
}

// AllocateIDs mocks base method.
func (m *MockDatastoreClient) AllocateIDs(ctx context.Context, keys []*datastore.Key) ([]*datastore.Key, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "AllocateIDs", ctx, keys)
	ret0, _ := ret[0].([]*datastore.Key)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// AllocateIDs indicates an expected call of AllocateIDs.
func (mr *MockDatastoreClientMockRecorder) AllocateIDs(ctx, keys any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "AllocateIDs", reflect.TypeOf((*MockDatastoreClient)(nil).AllocateIDs), ctx, keys)
}

// Close mocks base method.
func (m *MockDatastoreClient) Close() error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Close")
	ret0, _ := ret[0].(error)
	return ret0
}

// Close indicates an expected call of Close.
func (mr *MockDatastoreClientMockRecorder) Close() *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Close", reflect.TypeOf((*MockDatastoreClient)(nil).Close))
}

// Count mocks base method.
func (m *MockDatastoreClient) Count(ctx context.Context, q entitystore.Query) (int, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Count", ctx, q)
	ret0, _ := ret[0].(int)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// Count indicates an expected call of Count.
func (mr *MockDatastoreClientMockRecorder) Count(ctx, q any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Count", reflect.TypeOf((*MockDatastoreClient)(nil).Count), ctx, q)
}

// Delete mocks base method.
func (m *MockDatastoreClient) Delete(ctx context.Context, key *datastore.Key) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Delete", ctx, key)
	ret0, _ := ret[0].(error)
	return ret0
}

// Delete indicates an expected call of Delete.
func (mr *MockDatastoreClientMockRecorder) Delete(ctx, key any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Delete", reflect.TypeOf((*MockDatastoreClient)(nil).Delete), ctx, key)
}

// DeleteMulti mocks base method.
func (m *MockDatastoreClient) DeleteMulti(ctx context.Context, keys []*datastore.Key) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "DeleteMulti", ctx, keys)
	ret0, _ := ret[0].(error)
	return ret0
}

// DeleteMulti indicates an expected call of DeleteMulti.
func (mr *MockDatastoreClientMockRecorder) DeleteMulti(ctx, keys any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "DeleteMulti", reflect.TypeOf((*MockDatastoreClient)(nil).DeleteMulti), ctx, keys)
}

// Get mocks base method.
func (m *MockDatastoreClient) Get(ctx context.Context, key *datastore.Key, dst any) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Get", ctx, key, dst)
	ret0, _ := ret[0].(error)
	return ret0
}

// Get indicates an expected call of Get.
func (mr *MockDatastoreClientMockRecorder) Get(ctx, key, dst any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Get", reflect.TypeOf((*MockDatastoreClient)(nil).Get), ctx, key, dst)
}

// GetAll mocks base method.
func (m *MockDatastoreClient) GetAll(ctx context.Context, q entitystore.Query, dst any) ([]*datastore.Key, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetAll", ctx, q, dst)
	ret0, _ := ret[0].([]*datastore.Key)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetAll indicates an expected call of GetAll.
func (mr *MockDatastoreClientMockRecorder) GetAll(ctx, q, dst any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetAll", reflect.TypeOf((*MockDatastoreClient)(nil).GetAll), ctx, q, dst)
}

// GetAllWithOptions mocks base method.
func (m *MockDatastoreClient) GetAllWithOptions(ctx context.Context, q entitystore.Query, dst any, opts ...datastore.RunOption) (datastore.GetAllWithOptionsResult, error) {
	m.ctrl.T.Helper()
	varargs := []any{ctx, q, dst}
	for _, a := range opts {
		varargs = append(varargs, a)
	}
	ret := m.ctrl.Call(m, "GetAllWithOptions", varargs...)
	ret0, _ := ret[0].(datastore.GetAllWithOptionsResult)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetAllWithOptions indicates an expected call of GetAllWithOptions.
func (mr *MockDatastoreClientMockRecorder) GetAllWithOptions(ctx, q, dst any, opts ...any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	varargs := append([]any{ctx, q, dst}, opts...)
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetAllWithOptions", reflect.TypeOf((*MockDatastoreClient)(nil).GetAllWithOptions), varargs...)
}

// GetMulti mocks base method.
func (m *MockDatastoreClient) GetMulti(ctx context.Context, keys []*datastore.Key, dst any) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetMulti", ctx, keys, dst)
	ret0, _ := ret[0].(error)
	return ret0
}

// GetMulti indicates an expected call of GetMulti.
func (mr *MockDatastoreClientMockRecorder) GetMulti(ctx, keys, dst any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetMulti", reflect.TypeOf((*MockDatastoreClient)(nil).GetMulti), ctx, keys, dst)
}

// Mutate mocks base method.
func (m *MockDatastoreClient) Mutate(ctx context.Context, muts ...*datastore.Mutation) ([]*datastore.Key, error) {
	m.ctrl.T.Helper()
	varargs := []any{ctx}
	for _, a := range muts {
		varargs = append(varargs, a)
	}
	ret := m.ctrl.Call(m, "Mutate", varargs...)
	ret0, _ := ret[0].([]*datastore.Key)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// Mutate indicates an expected call of Mutate.
func (mr *MockDatastoreClientMockRecorder) Mutate(ctx any, muts ...any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	varargs := append([]any{ctx}, muts...)
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Mutate", reflect.TypeOf((*MockDatastoreClient)(nil).Mutate), varargs...)
}

// NewTransaction mocks base method.
func (m *MockDatastoreClient) NewTransaction(ctx context.Context, opts ...datastore.TransactionOption) (*datastore.Transaction, error) {
	m.ctrl.T.Helper()
	varargs := []any{ctx}
	for _, a := range opts {
		varargs = append(varargs, a)
	}
	ret := m.ctrl.Call(m, "NewTransaction", varargs...)
	ret0, _ := ret[0].(*datastore.Transaction)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// NewTransaction indicates an expected call of NewTransaction.
func (mr *MockDatastoreClientMockRecorder) NewTransaction(ctx any, opts ...any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	varargs := append([]any{ctx}, opts...)
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "NewTransaction", reflect.TypeOf((*MockDatastoreClient)(nil).NewTransaction), varargs...)
}

// Put mocks base method.
func (m *MockDatastoreClient) Put(ctx context.Context, key *datastore.Key, src any) (*datastore.Key, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Put", ctx, key, src)
	ret0, _ := ret[0].(*datastore.Key)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// Put indicates an expected call of Put.
func (mr *MockDatastoreClientMockRecorder) Put(ctx, key, src any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Put", reflect.TypeOf((*MockDatastoreClient)(nil).Put), ctx, key, src)
}

// PutMulti mocks base method.
func (m *MockDatastoreClient) PutMulti(ctx context.Context, keys []*datastore.Key, src any) ([]*datastore.Key, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "PutMulti", ctx, keys, src)
	ret0, _ := ret[0].([]*datastore.Key)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// PutMulti indicates an expected call of PutMulti.
func (mr *MockDatastoreClientMockRecorder) PutMulti(ctx, keys, src any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "PutMulti", reflect.TypeOf((*MockDatastoreClient)(nil).PutMulti), ctx, keys, src)
}

// PutMultiWithOptions mocks base method.
func (m *MockDatastoreClient) PutMultiWithOptions(ctx context.Context, reqs []*datastore.PutRequest, opts ...datastore.PutOption) ([]*datastore.Key, error) {
	m.ctrl.T.Helper()
	varargs := []any{ctx, reqs}
	for _, a := range opts {
		varargs = append(varargs, a)
	}
	ret := m.ctrl.Call(m, "PutMultiWithOptions", varargs...)
	ret0, _ := ret[0].([]*datastore.Key)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// PutMultiWithOptions indicates an expected call of PutMultiWithOptions.
func (mr *MockDatastoreClientMockRecorder) PutMultiWithOptions(ctx, reqs any, opts ...any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	varargs := append([]any{ctx, reqs}, opts...)
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "PutMultiWithOptions", reflect.TypeOf((*MockDatastoreClient)(nil).PutMultiWithOptions), varargs...)
}

// PutWithOptions mocks base method.
func (m *MockDatastoreClient) PutWithOptions(ctx context.Context, req *datastore.PutRequest, opts ...datastore.PutOption) (*datastore.Key, error) {
	m.ctrl.T.Helper()
	varargs := []any{ctx, req}
	for _, a := range opts {
		varargs = append(varargs, a)
	}
	ret := m.ctrl.Call(m, "PutWithOptions", varargs...)
	ret0, _ := ret[0].(*datastore.Key)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// PutWithOptions indicates an expected call of PutWithOptions.
func (mr *MockDatastoreClientMockRecorder) PutWithOptions(ctx, req any, opts ...any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	varargs := append([]any{ctx, req}, opts...)
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "PutWithOptions", reflect.TypeOf((*MockDatastoreClient)(nil).PutWithOptions), varargs...)
}

// ReserveIDs mocks base method.
func (m *MockDatastoreClient) ReserveIDs(ctx context.Context, keys []*datastore.Key) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "ReserveIDs", ctx, keys)
	ret0, _ := ret[0].(error)
	return ret0
}

// ReserveIDs indicates an expected call of ReserveIDs.
func (mr *MockDatastoreClientMockRecorder) ReserveIDs(ctx, keys any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "ReserveIDs", reflect.TypeOf((*MockDatastoreClient)(nil).ReserveIDs), ctx, keys)
}

// Run mocks base method.
func (m *MockDatastoreClient) Run(ctx context.Context, q entitystore.Query) *datastore.Iterator {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Run", ctx, q)
	ret0, _ := ret[0].(*datastore.Iterator)
	return ret0
}

// Run indicates an expected call of Run.
func (mr *MockDatastoreClientMockRecorder) Run(ctx, q any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Run", reflect.TypeOf((*MockDatastoreClient)(nil).Run), ctx, q)
}

// RunAggregationQuery mocks base method.
func (m *MockDatastoreClient) RunAggregationQuery(ctx context.Context, aq *datastore.AggregationQuery) (datastore.AggregationResult, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "RunAggregationQuery", ctx, aq)
	ret0, _ := ret[0].(datastore.AggregationResult)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// RunAggregationQuery indicates an expected call of RunAggregationQuery.
func (mr *MockDatastoreClientMockRecorder) RunAggregationQuery(ctx, aq any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "RunAggregationQuery", reflect.TypeOf((*MockDatastoreClient)(nil).RunAggregationQuery), ctx, aq)
}

// RunAggregationQueryWithOptions mocks base method.
func (m *MockDatastoreClient) RunAggregationQueryWithOptions(ctx context.Context, aq *datastore.AggregationQuery, opts ...datastore.RunOption) (datastore.AggregationWithOptionsResult, error) {
	m.ctrl.T.Helper()
	varargs := []any{ctx, aq}
	for _, a := range opts {
		varargs = append(varargs, a)
	}
	ret := m.ctrl.Call(m, "RunAggregationQueryWithOptions", varargs...)
	ret0, _ := ret[0].(datastore.AggregationWithOptionsResult)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// RunAggregationQueryWithOptions indicates an expected call of RunAggregationQueryWithOptions.
func (mr *MockDatastoreClientMockRecorder) RunAggregationQueryWithOptions(ctx, aq any, opts ...any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	varargs := append([]any{ctx, aq}, opts...)
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "RunAggregationQueryWithOptions", reflect.TypeOf((*MockDatastoreClient)(nil).RunAggregationQueryWithOptions), varargs...)
}

// RunInTransaction mocks base method.
func (m *MockDatastoreClient) RunInTransaction(ctx context.Context, f func(*datastore.Transaction) error, opts ...datastore.TransactionOption) (*datastore.Commit, error) {
	m.ctrl.T.Helper()
	varargs := []any{ctx, f}
	for _, a := range opts {
		varargs = append(varargs, a)
	}
	ret := m.ctrl.Call(m, "RunInTransaction", varargs...)
	ret0, _ := ret[0].(*datastore.Commit)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// RunInTransaction indicates an expected call of RunInTransaction.
func (mr *MockDatastoreClientMockRecorder) RunInTransaction(ctx, f any, opts ...any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	varargs := append([]any{ctx, f}, opts...)
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "RunInTransaction", reflect.TypeOf((*MockDatastoreClient)(nil).RunInTransaction), varargs...)
}

// RunWithOptions mocks base method.
func (m *MockDatastoreClient) RunWithOptions(ctx context.Context, q entitystore.Query, opts ...datastore.RunOption) *datastore.Iterator {
	m.ctrl.T.Helper()
	varargs := []any{ctx, q}
	for _, a := range opts {
		varargs = append(varargs, a)
	}
	ret := m.ctrl.Call(m, "RunWithOptions", varargs...)
	ret0, _ := ret[0].(*datastore.Iterator)
	return ret0
}

// RunWithOptions indicates an expected call of RunWithOptions.
func (mr *MockDatastoreClientMockRecorder) RunWithOptions(ctx, q any, opts ...any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	varargs := append([]any{ctx, q}, opts...)
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "RunWithOptions", reflect.TypeOf((*MockDatastoreClient)(nil).RunWithOptions), varargs...)
}

// WithReadOptions mocks base method.
func (m *MockDatastoreClient) WithReadOptions(ro ...datastore.ReadOption) *datastore.Client {
	m.ctrl.T.Helper()
	varargs := []any{}
	for _, a := range ro {
		varargs = append(varargs, a)
	}
	ret := m.ctrl.Call(m, "WithReadOptions", varargs...)
	ret0, _ := ret[0].(*datastore.Client)
	return ret0
}

// WithReadOptions indicates an expected call of WithReadOptions.
func (mr *MockDatastoreClientMockRecorder) WithReadOptions(ro ...any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "WithReadOptions", reflect.TypeOf((*MockDatastoreClient)(nil).WithReadOptions), ro...)
}
